# Generated by Django 2.2.3 on 2019-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.TextField()),
                ('brief_description_of_data', models.TextField()),
                ('datasets_available', models.TextField()),
                ('brief_description_of_datasets', models.TextField()),
                ('country', models.TextField()),
                ('api_documentation', models.TextField()),
            ],
        ),
    ]
